default_platform(:ios)

platform :ios do
  desc "Release the app into the App Store"
  lane :build_release do |options|
      required_parameters = [:version]

      # Increment build number
      increment_build_number

      # Increment version number
      version_number = options[:version]
      increment_version_number(
          version_number: version_number
      )

      # Commit
      git_add(path: '.')
      git_commit(
          path: '.',
          message: "Build v#{version_number}"
      )

      # Create release tag
      add_git_tag(
          tag: "v#{version_number}"
      )
      
      # Push to GitHub
      push_to_git_remote(
          remote: "origin",
          local_branch: "main",
          remote_branch: "main",
          force: true,
          force_with_lease: true,
          tags: true,
          no_verify: true,
          set_upstream: true
      )
  end
end